// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Program_Agregat.Entities;

namespace Program_Agregat.Migrations
{
    [DbContext(typeof(ProgramContext))]
    partial class ProgramContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Program_Agregat.Entities.PredlogPlana", b =>
                {
                    b.Property<Guid>("PredlogPlanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojDokumenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumDokumenta")
                        .HasColumnType("datetime2");

                    b.Property<string>("MisljenjeKomisije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgramPlanaProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Usvojen")
                        .HasColumnType("bit");

                    b.HasKey("PredlogPlanaId");

                    b.HasIndex("ProgramPlanaProgramId");

                    b.ToTable("PredloziPlana");
                });

            modelBuilder.Entity("Program_Agregat.Entities.ProgramEntity", b =>
                {
                    b.Property<Guid>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Licitacije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaksimalnoOgranicenje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProgramId");

                    b.ToTable("Programi");
                });

            modelBuilder.Entity("Program_Agregat.Entities.PredlogPlana", b =>
                {
                    b.HasOne("Program_Agregat.Entities.ProgramEntity", "ProgramPlana")
                        .WithMany()
                        .HasForeignKey("ProgramPlanaProgramId");

                    b.Navigation("ProgramPlana");
                });
#pragma warning restore 612, 618
        }
    }
}
