// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zalba.Entities;

namespace Zalba.Migrations
{
    [DbContext(typeof(ZalbaContext))]
    [Migration("20220223145524_nova")]
    partial class nova
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zalba.Entities.TipZalbe", b =>
                {
                    b.Property<Guid>("TipZalbeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivTipa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipZalbeId");

                    b.ToTable("TipoviZalbi");

                    b.HasData(
                        new
                        {
                            TipZalbeId = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36"),
                            NazivTipa = "Žalba na tok javnog nadmetanaja"
                        },
                        new
                        {
                            TipZalbeId = new Guid("21ad52f8-0281-4241-98b0-481566d25e4f"),
                            NazivTipa = "Žalba na Odluku o davanju u zakup"
                        },
                        new
                        {
                            TipZalbeId = new Guid("9d8bab08-f442-4297-8ab5-ddfe08e335f3"),
                            NazivTipa = "Žalba na Odluku o davanju na korišćenje"
                        });
                });

            modelBuilder.Entity("Zalba.Entities.ZalbaM", b =>
                {
                    b.Property<Guid>("ZalbaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojOdluke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojResenja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumPodnosenjaZalbe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumResenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Obrazlozenje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PodnosilacZalbe")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RadnjaNaOsnovuZalbe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazlogZalbe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusZalbe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TipZalbeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ZalbaId");

                    b.HasIndex("TipZalbeId");

                    b.ToTable("Zalbe");

                    b.HasData(
                        new
                        {
                            ZalbaId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            BrojOdluke = "S001",
                            BrojResenja = "S123",
                            DatumPodnosenjaZalbe = new DateTime(2020, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumResenja = new DateTime(2022, 2, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Obrazlozenje = "obrazlozenje",
                            RadnjaNaOsnovuZalbe = "JN ne ide u drugi krug",
                            RazlogZalbe = "razlog",
                            StatusZalbe = "Otvorena",
                            TipId = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36")
                        },
                        new
                        {
                            ZalbaId = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            BrojOdluke = "S002",
                            BrojResenja = "S124",
                            DatumPodnosenjaZalbe = new DateTime(2020, 11, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumResenja = new DateTime(2022, 2, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Obrazlozenje = "obrazlozenje",
                            RadnjaNaOsnovuZalbe = "JN ide u drugi krug sa novim uslovima",
                            RazlogZalbe = "razlog",
                            StatusZalbe = "Odbijena",
                            TipId = new Guid("044f3de0-a9dd-4c2e-b745-89976a1b2a36")
                        });
                });

            modelBuilder.Entity("Zalba.Entities.ZalbaM", b =>
                {
                    b.HasOne("Zalba.Entities.TipZalbe", null)
                        .WithMany("Zalbe")
                        .HasForeignKey("TipZalbeId");
                });

            modelBuilder.Entity("Zalba.Entities.TipZalbe", b =>
                {
                    b.Navigation("Zalbe");
                });
#pragma warning restore 612, 618
        }
    }
}
