// <auto-generated />
using System;
using Korisnik_agregat.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Korisnik_agregat.Migrations
{
    [DbContext(typeof(KorisnikContext))]
    partial class KorisnikContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Korisnik_agregat.Entities.Korisnik", b =>
                {
                    b.Property<Guid>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TipKorisnikaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KorisnikId");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikId = new Guid("34f11383-cb12-481d-9ff7-2fd458dc7e2b"),
                            Ime = "Vlado",
                            KorisnickoIme = "Vlado",
                            Lozinka = "Hp4FA+Davx87H1kjksH9KqfoQwWORWRuIIC/ORXK6bpf6L58i76CCzvr/hnhzP8cumQlxGwPdNw3T98Mi6opEdNB8YpyyQMP7I/r86lg7dw21/VWbLdBhxk8FkiQh7Zzx3ghShxochj9yvOKGcif8yiqqRcPnf8/FSNeBzyY9VierHh9SdHN4bw7kY5c5aI84yih2cJKQZXs3UHttYl/TvHDG+djhax22GZHn4joKbrxvkbi+OAZcDbekkWuK96MEziob/ROCBx7WKN8CQ+DHy50S36Zk/XZHWo+uXrUdk2xS35ii4J4Uxx5FFsof/h1KTz3ZaQpo8EHFd0H9QycrQ==",
                            Prezime = "Cetkovic",
                            Salt = "K0mnPR8m67LE2Q==",
                            TipKorisnikaID = new Guid("577a8f2b-1a55-4e91-a3ea-3d5cf16814a6")
                        });
                });

            modelBuilder.Entity("Korisnik_agregat.Entities.TipKorisnika", b =>
                {
                    b.Property<Guid>("TipKorisnikaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivTipa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipKorisnikaId");

                    b.ToTable("TipoviKorisnika");

                    b.HasData(
                        new
                        {
                            TipKorisnikaId = new Guid("411badd1-bee5-4bf4-9eab-138806fa8914"),
                            NazivTipa = "Operater"
                        },
                        new
                        {
                            TipKorisnikaId = new Guid("62d026f1-caf7-4eae-bf1a-261a95f7f0bb"),
                            NazivTipa = "Tehnički sekretar"
                        },
                        new
                        {
                            TipKorisnikaId = new Guid("6216bfa0-66d0-48e8-9014-ad1030f10140"),
                            NazivTipa = "Prva komisija"
                        },
                        new
                        {
                            TipKorisnikaId = new Guid("b02616e3-e14d-4548-ba2b-c064b6f21a98"),
                            NazivTipa = "Superuser"
                        },
                        new
                        {
                            TipKorisnikaId = new Guid("d7a63d05-c1f3-4936-9b70-f0b2b496d297"),
                            NazivTipa = "Operater nadmetanja"
                        },
                        new
                        {
                            TipKorisnikaId = new Guid("bcafc2c9-378b-42a5-8fb7-10a0c4726a22"),
                            NazivTipa = "Licitant"
                        },
                        new
                        {
                            TipKorisnikaId = new Guid("3634f986-0503-4369-a7ea-891517db5084"),
                            NazivTipa = "Menadžer"
                        },
                        new
                        {
                            TipKorisnikaId = new Guid("577a8f2b-1a55-4e91-a3ea-3d5cf16814a6"),
                            NazivTipa = "Administrator"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
