// <auto-generated />
using System;
using Licitacija_agregat.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Licitacija_agregat.Migrations
{
    [DbContext(typeof(LicitacijaContext))]
    [Migration("20220219195913_Izmene 2")]
    partial class Izmene2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Licitacija_agregat.Entities.Etapa", b =>
                {
                    b.Property<Guid>("EtapaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojEtape")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dan")
                        .HasColumnType("datetime2");

                    b.HasKey("EtapaId");

                    b.ToTable("Etape");
                });

            modelBuilder.Entity("Licitacija_agregat.Entities.Licitacija", b =>
                {
                    b.Property<Guid>("LicitacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Broj")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<int>("Korak_cene")
                        .HasColumnType("int");

                    b.Property<int>("Ogranicenje")
                        .HasColumnType("int");

                    b.Property<DateTime>("Rok_za_dostavljanje_prijave")
                        .HasColumnType("datetime2");

                    b.HasKey("LicitacijaId");

                    b.ToTable("Licitacije");
                });
#pragma warning restore 612, 618
        }
    }
}
