// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oglas_Agregat.Entities;

namespace Oglas_Agregat.Migrations
{
    [DbContext(typeof(OglasContext))]
    partial class OglasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Oglas_Agregat.Entities.Oglas", b =>
                {
                    b.Property<Guid>("OglasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumObjave")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("JavnoNadmetanjeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ObjavljenUListuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OpisOglasa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RokZaZalbu")
                        .HasColumnType("datetime2");

                    b.HasKey("OglasId");

                    b.HasIndex("ObjavljenUListuId");

                    b.ToTable("Oglasi");

                    b.HasData(
                        new
                        {
                            OglasId = new Guid("00f78e6b-a2bb-43b5-b3bb-f5708d1a5129"),
                            DatumObjave = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JavnoNadmetanjeId = new Guid("1ae8137b-1674-4c91-a4b5-87a133f5dd87"),
                            ObjavljenUListuId = new Guid("00f78e6b-a2bb-43b5-b3bb-f5708d1a5129"),
                            OpisOglasa = "fdafdafa",
                            RokZaZalbu = new DateTime(2000, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Oglas_Agregat.Entities.SluzbeniList", b =>
                {
                    b.Property<Guid>("SluzbeniListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojLista")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIzdanja")
                        .HasColumnType("datetime2");

                    b.HasKey("SluzbeniListId");

                    b.ToTable("SluzbeniListovi");

                    b.HasData(
                        new
                        {
                            SluzbeniListId = new Guid("00f78e6b-a2bb-43b5-b3bb-f5708d1a5129"),
                            BrojLista = 33,
                            DatumIzdanja = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Oglas_Agregat.Entities.Oglas", b =>
                {
                    b.HasOne("Oglas_Agregat.Entities.SluzbeniList", "ObjavljenUListu")
                        .WithMany("ListaOglasa")
                        .HasForeignKey("ObjavljenUListuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjavljenUListu");
                });

            modelBuilder.Entity("Oglas_Agregat.Entities.SluzbeniList", b =>
                {
                    b.Navigation("ListaOglasa");
                });
#pragma warning restore 612, 618
        }
    }
}
